name: flutter_rating_bar_pulse_example
description: Demonstrates how to use the flutter_rating_bar_pulse plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <5.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_rating_bar_pulse:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
