name: flutter_rating_bar_pulse
description: A simple yet fully customizable ratingbar for flutter which also include a rating bar indicator, supporting any fraction of rating.
version: 1.0.0
repository: https://github.com/chothanijaydip/flutter_rating_bar_pulse
homepage: https://chothanijaydip.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
